services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/misc-api/app
      - /usr/src/misc-api/app/node_modules
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
    env_file:
      - app/.env
    mem_limit: 1g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
